### ISSUE TITLE
Source code access request

### ISSUE THREAD

**Issue by Phoenix616** [Woodi-dev/Among-Us-Sheriff-Mod#34]
I am a user of your software which you [seem to distribute under the GPLv3](https://github.com/Woodi-dev/Among-Us-Sheriff-Mod#license) but I can't find any info regarding how one can request access to the source code which's right to access is granted to me under point 6 of the GPLv3. I guess this issue is my request?

**Comment by Woodi-dev** [comment]
https://github.com/Tobiti/Among-Us-Sheriff-Mod/

**Comment by mfekadu** [comment]
Hey @Woodi-dev,

I respect your desire to reduce the chance of supporting cheaters.

However, there are a couple of problems with the closed source code

1. @Phoenix616 is right, GNU GPLv3 does require that the source code be disclosed along when the license material is distributed. https://choosealicense.com/licenses/gpl-3.0/
2. The lack of source code may discourage players who worry about malicious code. Sharing your source code can allow players to inspect your code before installing the files to their computer, so that they can play with confidence. 

Please do share the source code for the sake of computer security and to maintain the integrity of your GNU GPLv3 license. 

Thanks,
Michael

**Comment by mfekadu** [comment]
Oh and a third reason

* Sharing the code allows other developers to contribute to making your `Among-Us-Sheriff-Mod` more robust! That's always fun 😄

**Comment by micah686** [comment]
> 
> 
> Hey @Woodi-dev,
> 
> I respect your desire to reduce the chance of supporting cheaters.
> 
> However, there are a couple of problems with the closed source code
> 
>     1. @Phoenix616 is right, GNU GPLv3 does require that the source code be disclosed along when the license material is distributed. https://choosealicense.com/licenses/gpl-3.0/
> 
>     2. The lack of source code may discourage players who worry about malicious code. Sharing your source code can allow players to inspect your code before installing the files to their computer, so that they can play with confidence.
> 
> 
> Please do share the source code for the sake of computer security and to maintain the integrity of your GNU GPLv3 license.
> 
> Thanks,
> Michael

There is also the fact that source code access is one of the main points for the GPL, and is required to be given upon request. If you don't want to give out the source code, I suggest you choose a different license type.

**Comment by mfekadu** [comment]
> source code access is one of the main points for the GPL
Good point @micah686 

In fact, it's possible that you _cannot_ choose another license -- except many another similar GPL license.

BepinEx uses LGPL-v2.1 (https://github.com/BepInEx/BepInEx/blob/master/LICENSE), which also requires that you 

1. Disclose source
2. **Use the same license** (cannot change) https://choosealicense.com/licenses/lgpl-2.1/

Therefore, it seems that you are legally required to do both of the above. 

Interesting. I never knew this before!

**Comment by Woodi-dev** [comment]
As i already mentioned i linked to the source code. Yes any modifications of bepinex require a LGPL-2.1 license. However, my modules do not underlay these conditions. I can change the license for a new version of the mod, but not for already published ones. I am actually about to close this project and further ones if one tries to take legal actions against me.

**Comment by mfekadu** [comment]
If BepInEx can be considered a "library" then you might be fine to change the license too @Woodi-dev 

I hope you'll keep the project open -- tons of developers would be glad to contribute and tons more gamers would be grateful for the mod.

**Comment by Zosh8818** [comment]
> As i already mentioned i linked to the source code. So i can share it. Yes any modifications of bepinex require a LGPL-2.1 license. However, my modules do not underlay these conditions. I can change the license for a new version of the mod, but not for already published ones. I am actually about to close this project and further ones if one tries to take legal actions against me.

Where's the source code? You didn't link anything. Your pretty sus not gonna lie.

**Comment by Phoenix616** [comment]
> Where's the source code? You didn't link anything. You're pretty sus not gonna lie.

https://github.com/Woodi-dev/Among-Us-Sheriff-Mod/issues/34#issuecomment-759085684

**Comment by micah686** [comment]
> 
> 
> As i already mentioned i linked to the source code. So i can share it. Yes any modifications of bepinex require a LGPL-2.1 license. However, my modules do not underlay these conditions. I can change the license for a new version of the mod, but not for already published ones. I am actually about to close this project and further ones if one tries to take legal actions against me.

It's not that likely that someone will be taking legal action against you due to how small the project is. 
## HOWEVER
The fact remains that your project is Listed under the GPL, and as such, you are **REQUIRED** to send the source code upon request. That's kind of the main point of the GPL. You can't build off of a community GPL code, and then release binaries without the source being available. You need to make the source code available in this repository, not another repo, as that repo isn't under your control, and could have introduced changes that aren't in your current code.

Also, even if you closed the project, that wouldn't make the licensing issues go away. Anyone that had the binary could still request copies of the source, since that's no different from a company taking down the binaries to a GPL program and then not releasing the source.

I don't believe you can also state the source code as being in another person's repository(especially since the one you linked it out of sync). Unfortunately, you have discovered some of the downsides of the "viral" nature of the GPL.
What you probably need to do is this:
- Release the source for the latest binary (**REQUIRED**)
- Change the license to something more restrictive, like MIT or Apache-2.0, making sure your code isn't under violation of the GPL.
- Any new changes would be under the new license, and not subject to copyright.

**Comment by Zosh8818** [comment]
The "source code" he posted from the other repository is not the same from the one you download since the download still link you to Woodi-dev's

**Comment by Woodi-dev** [comment]
Guys pls relax, i will upload the source code of the next and upcoming versions directly on this page
